version: '2'
services:
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: contacts
    volumes:
      - /var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq/

  discovery:
    build: eureka-server/.
    ports:
      - "8761:8761"

  contacts:
    build: contacts/.
    links:
      - postgres
      - discovery
    depends_on:
      - postgres
      - discovery

  # api:
  #   build: api/.
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - discovery
  #     - contacts
  #     - rabbitmq
  #   depends_on:
  #     - contacts

  edge:
    build: edge/.
    ports:
      - "8080:8080"
    links:
      - discovery
    depends_on:
      - discovery
