postgres:
  image: postgres:9.5
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: contacts
  volumes:
    - /var/lib/postgresql

discovery:
  build: eureka-server/.
  ports:
    - "8761:8761"

contacts:
  build: contacts/.
  links:
    - postgres
    - discovery
  # depends_on:
  #   - postgres
  #   - discovery
  mem_limit: 512M
  cpuset: "1"
  environment:
    EUREKA_URL: http://eureka:admin@discovery:8761/eureka
    DATABASE_URL: jdbc:postgresql://postgres:5432/contacts

# edge:
#   build: edge/.
#   ports:
#     - "8080:8080"
#   links:
#     - discovery
#   depends_on:
#     - discovery

# hystrix:
#   build: hystrix/.
#   ports:
#     - "8090:8090"
#   links:
#     - discovery
