server:  
  port: 8080

spring:  
  application:
    name: api-entrypoint
eureka:  
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true