zuul:
  routes:
    contacts-service:
      path: /contacts/**
      stripPrefix: true
      serviceId: contacts-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: false

---

spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@discovery:8761/eureka/
  instance:
    preferIpAddress: false
